### PR TITLE
Add unlocked taskbar appearance, lock taskbar setting

### PR DESCRIPTION
**Pull request by dremin**
Adds an unlocked appearance for the taskbar, and a setting to control it, unlocked by default. There is no actual unlocked behavior, it is just for appearance currently.

### CODE REVIEW

**Comment by dremin** [comment]
Because this is for appearance, and not unlocked behavior (such as moving toolbars), should this be labeled differently in the menu and settings?

**Comment by xoascf** [comment]
It looks very nice, but I think it would be better if it had a function that is already implemented, like changing the location.
The behavior is simple: when the taskbar is unlocked, you can drag to any of the four sides of the screen starting from the center of the screen, ignoring this action if the cursor is still on the taskbar (so there would be no wrong dragging when moving the cursor from side to side).

> Because this is for appearance, and not unlocked behavior (such as moving toolbars), should this be labeled differently in the menu and settings?

In case it is not implemented, it would be preferable to put it on hold until at least the edge change thing can be done, both resizing the taskbar and moving the toolbars I think can wait.

**Comment by dremin** [comment]
> It looks very nice, but I think it would be better if it had a function that is already implemented, like changing the location. The behavior is simple: when the taskbar is unlocked, you can drag to any of the four sides of the screen starting from the center of the screen, ignoring this action if the cursor is still on the taskbar (so there would be no wrong dragging when moving the cursor from side to side).
> 
> > Because this is for appearance, and not unlocked behavior (such as moving toolbars), should this be labeled differently in the menu and settings?
> 
> In case it is not implemented, it would be preferable to put it on hold until at least the edge change thing can be done, both resizing the taskbar and moving the toolbars I think can wait.

Thanks! Good idea, I agree. I will add the edge change functionality.

**Comment by dremin** [comment]
@xoascf I've added the edge change via drag. Could you please check that it works on your machine as well?

**Review by xoascf — COMMENTED** [review]
It lags a bit when moving around the screen, although I'm not sure if it's the AppBar implementation, since the problem is the same when changing the location in Properties.
While dragging, you can right-click to lock the taskbar again, and it will still allow dragging until the click is released.

**Comment by dremin** [comment]
@xoascf 

> It lags a bit when moving around the screen, although I'm not sure if it's the AppBar implementation, since the problem is the same when changing the location in Properties.

Some of the lag and flicker can be fixed. I pushed one fix, the other fixes I have made will come via ManagedShell updates. There will likely still be some lag from the shell changing workarea.

> While dragging, you can right-click to lock the taskbar again, and it will still allow dragging until the click is released.

Thanks for finding this one, fixed!

**Review by xoascf — APPROVED** [review]

**Pull request merged**
