### PR TITLE
i can't put app shortcuts on the taskbar

### PR DESCRIPTION
**Pull request by selmofajardo**
i can't put app shortcuts on the taskbar, just next to the clock, how do i put shortcuts on the taskbar?

### CODE REVIEW

**Comment by xoascf** [comment]
> i can't put app shortcuts on the taskbar, just next to the clock, how do i put shortcuts on the taskbar?

Use the Quick launch feature:
image

**Comment by selmofajardo** [comment]
I can't put shortcuts on the taskbar

**Comment by selmofajardo** [comment]
this option that you passed is already correct, but I can't put shortcut in the TASK BAR.

**Comment by selmofajardo** [comment]
thanks, i got it, i pointed the fastboot path to a folder with the shortcuts, and it worked.

**Comment by selmofajardo** [comment]
Is there a way to group the windows of the programs, for example the minimized windows of google chrome, there are several occupying the entire taskbar, is there a way to group? I can't group the programs.

**Comment by selmofajardo** [comment]
the windows are like in windows 98 and xp, they are distributed on the taskbar, occupying the entire taskbar

**Comment by xoascf** [comment]
> Is there a way to group the windows of the programs, for example the minimized windows of google chrome, there are several occupying the entire taskbar, is there a way to group? I can't group the programs.

The XP's taskbar grouping feature is not yet available.

**Pull request closed without merging**
