### PR TITLE
Add Windows XP Silver theme

### LINKED ISSUE #115: [Request] Windows XP Silver theme
I tended to use the silver theme on Windows XP, and my high school used it too.

### LINKED ISSUE #141: [Request] Windows XP Silver Taskbar
Can you please add Windows XP Silver color to the taskbar?

### PR DESCRIPTION
**Pull request by xoascf**
A reproduction of the original Windows XP Silver theme design!

- It uses the Windows XP Blue design as merged dictionary to reduce the size of the theme and not be redundant
- Tray toggle button states are more accurate now (5de553f)
- More accurate spin buttons were added (ab24c09), but may require more work
- Also fixes the task button padding, margins and size of the Windows XP "start" button
- Closes #115
- Closes #141

### CODE REVIEW

**Comment by dremin** [comment]
Nice, this is a very good start! Which part of the notification area toggle do you need help with specifically?

**Comment by xoascf** [comment]
> Nice, this is a very good start! Which part of the notification area toggle do you need help with specifically?

Mainly the toggle button states on the tray, it uses a fill with some kind of detailed reflection
[TrayToggle.zip](https://github.com/dremin/RetroBar/files/7577155/TrayToggle.zip)
.

**Comment by dremin** [comment]
I pushed some improvements. The tray toggle isn't perfect, but is closer.

**Comment by xoascf** [comment]
> I pushed some improvements. The tray toggle isn't perfect, but is closer.

That's great, thanks! Now I'm going to make some small changes to get this ready to merge.

**Comment by dremin** [comment]
Are you planning to add any further changes or is this good to merge? It is looking pretty good to me. I think the scroll buttons could use a little bit more work, but they're a massive improvement as it stands.

**Comment by xoascf** [comment]
> Are you planning to add any further changes or is this good to merge? It is looking pretty good to me. I think the scroll buttons could use a little bit more work, but they're a massive improvement as it stands.

I'm done for now, I hope the scroll buttons can be worked on in another PR later.

**Pull request merged**
