### PR TITLE
Hebrew language support

### PR DESCRIPTION
**Pull request by novatiberium**
A week ago, we got a build of RetroBar that added the RtL abilities. I have a file of the Hebrew translation ready to be used. I might make pictures (unless someone can lol) cause I'm busy right now with stuff and I've been hit on mental issues recently.
[‎⁨עברית (ישראל ואלברטה)⁩.xaml.zip](https://github.com/dremin/RetroBar/files/7448177/xaml.zip)

### CODE REVIEW

**Comment by xoascf** [comment]
Hey, be careful, you are adding a lot of already existing commits to the branch, it would be better if you reset your working branch, and then commit only the changes you want to add.

**Comment by novatiberium** [comment]
> 
> 
> Hey, be careful, you are adding a lot of already existing commits to the branch, it would be better if you reset your working branch, and then commit only the changes you want to add.

Oh I'm so sorry, I'm just new to GitHub and I was trying to understand a few things. I just thought that branch had enough language commits for me to add my Hebrew stuff here. While I am disappointed my Hebrew files were not in the latest update, I hope something can be done in hopes of having it here in the next release. Maybe should I reupload or you guys would like to handle it yourselves?

**Comment by xoascf** [comment]
> > 
> 
> > 
> 
> > Hey, be careful, you are adding a lot of already existing commits to the branch, it would be better if you reset your working branch, and then commit only the changes you want to add.
> 
> 
> 
> Oh I'm so sorry, I'm just new to GitHub and I was trying to understand a few things. I just thought that branch had enough language commits for me to add my Hebrew stuff here. While I am disappointed my Hebrew files were not in the latest update, I hope something can be done in hopes of having it here in the next release. Maybe should I reupload or you guys would like to handle it yourselves?

I will make a PR regarding the changes needed for the new updates in the translations, you can close this PR if you don't have any inconvenience.

**Comment by novatiberium** [comment]
> 
> 
> > > 
> > 
> > 
> > > 
> > 
> > 
> > > Hey, be careful, you are adding a lot of already existing commits to the branch, it would be better if you reset your working branch, and then commit only the changes you want to add.
> > 
> > 
> > Oh I'm so sorry, I'm just new to GitHub and I was trying to understand a few things. I just thought that branch had enough language commits for me to add my Hebrew stuff here. While I am disappointed my Hebrew files were not in the latest update, I hope something can be done in hopes of having it here in the next release. Maybe should I reupload or you guys would like to handle it yourselves?
> 
> I will make a PR regarding the changes needed for the new updates in the translations, you can close this PR if you don't have any inconvenience.

Hey bud! Thank you hopefully. However since I believe some of the translation could be _incorrect_ or something, I'll leave this open for now so anyone interested in modifying the thing can submit here.

**Comment by dremin** [comment]
> I will make a PR regarding the changes needed for the new updates in the translations, you can close this PR if you don't have any inconvenience.

@xoascf If you still plan on doing this, I'll close this PR when I see yours. Otherwise I can put a PR together.

**Comment by dremin** [comment]
Closing now that #176 is merged. Thanks for the translation @novatiberium!

**Pull request closed without merging**
