### PR TITLE
Notification balloon support

### PR DESCRIPTION
**Pull request by dremin**
- Adds support for classic style balloon notifications (#51)
- If notification area is collapsed, an icon displaying a balloon will be promoted
- Improved tooltip styles
- Fixed task button width calculation
- Fixed collapsed notification area state issue when changing themes

### CODE REVIEW

**Comment by xoascf** [comment]
It would be nice if it would play the default "System Notification" (HKEY_CURRENT_USER\AppEvents\Schemes\Apps\.Default\SystemNotification\.Current) like in Windows XP when the notification balloons appear.
It used to sound like...
Original source (high quality): https://puu.sh/If5ND/40eb044f87.WAV
Released (low quality): https://puu.sh/If5OH/13e214d50b.wav

**Comment by dremin** [comment]
> It would be nice if it would play the default "System Notification" (**`HKEY_CURRENT_USER\AppEvents\Schemes\Apps\.Default\SystemNotification\.Current`**) like in Windows XP when the notification balloons appear. It used to sound like... Original source (high quality): https://puu.sh/If5ND/40eb044f87.WAV Released (low quality): https://puu.sh/If5OH/13e214d50b.wav

Good idea, I'll add this! It seems like in Windows 8.1 and later, the appropriate system sound to play is `Notification.Default`, while it is `SystemNotification` on Windows 7 and earlier.

**Comment by xoascf** [comment]
Great! I missed that sound...


Now there are only two minor issues:
1. The sound plays through the app session instead of the system notification sounds session. I was almost startled(?) to hear the notification sound too loud when a balloon came out.

2. I realized I was wrong, in Windows XP, the system balloon sound location in the registry is:
`HKEY_CURRENT_USER\AppEvents\Schemes\Apps\.Default\SystemNotification\.Current`
But in Windows Vista, 7 or [8+ (11 as well)](https://winaero.com/enable-balloon-notifications-in-windows-10-and-disable-toasts/), the sound is located in:
`HKEY_CURRENT_USER\AppEvents\Schemes\Apps\Explorer\SystemNotification\.Current`
It shouldn't use the notification sound for metro/modern apps with "toast notifications" which is `Notification.Default`.
See here for more information: https://winaero.com/fix-windows-plays-no-sound-for-tray-balloon-tips-notifications/

I can fix both for tomorrow, so this is recorded here just in case.

**Comment by xoascf** [comment]
Commit with fixes here: https://github.com/cairoshell/ManagedShell/pull/37

**Comment by xoascf** [comment]
I'm not sure if this is a bug, but when the balloon tip title is multiline, it makes the balloon become multiline, as opposed to the Windows default behavior of making it single line.

**Comment by dremin** [comment]
> I'm not sure if this is a bug, but when the balloon tip title is multiline, it makes the balloon become multiline, as opposed to the Windows default behavior of making it single line. Also, when no tip icon is selected for the notification, it leaves a space for the icon, not present since the implementation in Windows (ME/2k).

The multiline title was intentional, but I didn't check how long titles behave on 2k/XP, so it doesn't surprise me that I got it wrong. The goal is to be as accurate as possible, so I'll take another look.

I'll also take a look at fixing the no-icon scenario.

**Pull request merged**
