### PR TITLE
Update Russian translation

### PR DESCRIPTION
**Pull request by 1280px**

### CODE REVIEW

**Comment by 111ebobo** [comment]
It`s no need to do it now, better add Ukrainian

**Comment by 1280px** [comment]
> It`s no need to do it now, better add Ukrainian

IIRC someone was working on Ukrainian locale at some point, though they didn't finish it. You can try to finish it yourself and then pull request, and it will probably by accepted.

**Comment by 111ebobo** [comment]
> > It`s no need to do it now, better add Ukrainian
> 
> IIRC someone was working on Ukrainian locale at some point, though they didn't finish it. You can try to finish it yourself and then pull request, and it will probably by accepted. 

I tried once to translate it but it didn't work

**Comment by dremin** [comment]
Thanks!

**Pull request merged**
