### PR TITLE
Add Windows XP Zune Style Theme and Windows XP Embedded Style Theme

### PR DESCRIPTION
**Pull request by mutoyoru**
I recreated the Windows XP Zune Style theme for the RetroBar, using resources from msstyle file and StyleBuilder program on XP. Zune Style theme is based on Windows XP Blue XAML file. I didn't do scroll buttons since there aren't any usage for them at the moment, but I'll update it if it becomes necessary. If there is a mistake or a part needs to be fixed please notify me. I'm also uploading unpacked Zune mssstyle file as zip file.

Screenshot:
Screenshot 2022-03-02 231932

Unpacked Zuna msstyle file:
[zune_mssstyles_unpacked.zip](https://github.com/dremin/RetroBar/files/8172684/zune_mssstyles_unpacked.zip)

### CODE REVIEW

**Comment by mutoyoru** [comment]
When selecting Zune theme on the build created from Github Actions, RetroBar crashes. But manually showing theme to RetroBar 1.7 does work and there are no crashes. I tried to look at and see if there is anything misplaced but couldn't find it.

**Comment by xoascf** [comment]
It looks pretty good, however, there are 2 small problems:
- Need to add a reference for the button image in the project (it will crash otherwise)
- You need to reference the original XAML theme, you can choose one of these themes already worked with the base design to avoid redundancy and larger size:
  - Windows XP Blue
  - Windows XP Royale
 
You can see why:
Comparison

**Comment by mutoyoru** [comment]
Completely forgot about project file. There should be no problem, now. I also tweaked theme a little bit closer to original and did the changes.

**Comment by dremin** [comment]
This is pretty good, thanks! I have a few small suggestions:

- The light lines on the left and right sides of taskbar buttons in this theme aren't present in the msstyles, could that be adjusted? I believe setting the inner left and right border colors to Transparent should do the trick.
- There should be a light-ish line in the first pixel (or rightmost when vertical) of the taskbar and tray background gradient
- There should be a margin between taskbar buttons like the Royale theme
- The tray expander button doesn't look quite right to me- the arrow is too big and bright, and the button isn't centered. Maybe using the Royale theme as a base rather than Blue would help here, since they are pretty similar?
- Could you do the scroll buttons? If you open a lot of windows, you'll see them :)

**Comment by mutoyoru** [comment]
I've made the changes. Also added Embedded Style theme since it's pretty similar to Royale and Zune theme except color scheme.

Zune Style Screenshot:
Screenshot 2022-03-04 234306

Embedded Style Screenshot:
Screenshot 2022-03-04 234530

**Comment by dremin** [comment]
This looks good, thanks!

**Pull request merged**
