### PR TITLE
Filter out the Tombstones folder from quick launch (#856)

### PR DESCRIPTION
**Pull request by dremin**

### CODE REVIEW

**Comment by xoascf** [comment]
It doesn't just hide the folders in that path, I remember it only does that for hidden items, maybe the "Tombstones" folder is set to hidden in its properties.

**Comment by dremin** [comment]
> It doesn't just hide the folders in that path, I remember it only does that for hidden items, maybe the "Tombstones" folder is set to hidden in its properties.

I don't quite understand, are you seeing this change hide items unintentionally?

**Comment by xoascf** [comment]
> > It doesn't just hide the folders in that path, I remember it only does that for hidden items, maybe the "Tombstones" folder is set to hidden in its properties.
> 
> I don't quite understand, are you seeing this change hide items unintentionally?

If an item in a path selected for Quick Launch has the "Hidden" property set, it will not be displayed:
prophidden

**Comment by dremin** [comment]
> > > It doesn't just hide the folders in that path, I remember it only does that for hidden items, maybe the "Tombstones" folder is set to hidden in its properties.
> > 
> > 
> > I don't quite understand, are you seeing this change hide items unintentionally?
> 
> If an item in a path selected for Quick Launch has the "Hidden" property set, it will not be displayed: prophidden

Oh! Yeah, that is expected and RetroBar behaves the same way. For some reason it seems like when the system creates the Tombstones folder, it is not marked as hidden, so it still shows in RetroBar.

**Comment by xoascf** [comment]
A bit hacky, at least here it was hidden by default, I thought it would be better to advise the user to "hide" this folder? I guess that could work as a workaround, or the classic `%UserProfile%\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch` could be used by default instead?

**Comment by dremin** [comment]
I am fixing the hidden file handling in ManagedShell here: https://github.com/cairoshell/ManagedShell/pull/115

Hopefully this is sufficient to fix this issue. Will abandon this PR for now and revive it if it turns out Windows does not hide this folder consistently.

**Pull request closed without merging**
