### PR TITLE
Add Vietnamese language for RetroBar

### PR DESCRIPTION
**Pull request by michioxd**
Add Vietnamese (Tiếng Việt) language for RetroBar

### CODE REVIEW

**Comment by xoascf** [comment]
You need to correct the name for the language to be used for the System to "Tiếng Việt" (Tiếng Việt.xaml).
Also, you will need to remove the references to "properties_95" and "properties_95_noclock" if you do not have the images localised for your language, or simply change them to:
```
    <BitmapImage x:Key="properties_95" UriSource="pack://siteoforigin:,,,/Resources/properties.png"/>
    <BitmapImage x:Key="properties_95_noclock" UriSource="pack://siteoforigin:,,,/Resources/properties_noclock.png"/>
```

**Comment by michioxd** [comment]
Did you mean correct the title of this pull?
Also I removed the references "properties_95" and "properties_95_noclock" as you said, thanks!

**Comment by xoascf** [comment]
> 
> 
> Did you mean correct the title of this pull?

No, I am referring to the .xaml translation file, strangely enough, the letter e does not match the correct diacritic of the language name (at least the one used by Windows), you can compare it with the result of the command:
`powershell [System.Globalization.CultureInfo]::CurrentUICulture.Parent.NativeName`
If the language name is different even by one character, the language is not automatically loaded by the system with that language name (this when "System" is chosen as the language).

**Comment by michioxd** [comment]
Ok thanks it work!

**Comment by dremin** [comment]
Awesome, thanks!

**Pull request merged**
