### PR TITLE
Add Turkish translation

### PR DESCRIPTION
**Pull request by mucbi**
This adds Turkish translation to RetroBar. Turkish translation is based on Windows XP Version 5.1 (Build 2600.xpsp_sp2_rtm.040803-2158: Service Pack 2). There are some things that are not available on Windows XP such as taskbar locations or font smoothing. These are taken form Windows 7 and "Microsoft Terminology/Style Guides" site.

### CODE REVIEW

**Comment by xoascf** [comment]
This is great, although there is one minor issue, rename the XAML file to "Türkçe.xaml", so that it loads as "System" for users who have their Windows language set to Turkish.

**Comment by mucbi** [comment]
Oops, looks like I forgot to change the file name. Fixed it now.

**Comment by xoascf** [comment]
Oh, I almost forgot, the access keys are missing, I think that would be the last thing.

**Comment by dremin** [comment]
Thanks!

**Pull request merged**
