### PR TITLE
Vista Aero and Basic themes

### LINKED ISSUE #15: Add Windows vista Theme
Would be very nice if u can add the Windows vista Taskbar Theme because i love the Design of it

and add more features like Old clock system and Change Icons

### PR DESCRIPTION
**Pull request by dremin**
Fixes #15

### CODE REVIEW

**Comment by 1280px** [comment]
Very cool!! I think the background should be a little more transparent, though
изображение

**Comment by ColdSalt09** [comment]
FINALLY !!!!!!! THANK YOU!!!!!!!!!

**Comment by dremin** [comment]
> When the start button will be fixed?

Working on it :)

**Comment by dremin** [comment]
> When the start button will be fixed?

The latest builds now no longer have the start button cut off.

**Comment by dremin** [comment]
> Very cool!! I think the background should be a little more transparent, though
> изображение

It varies a lot in Vista depending on the window color settings, I tried to pick something neutral.

**Pull request merged**
