### PR TITLE
Add Windows XP Royal Noir Theme

### PR DESCRIPTION
**Pull request by lpmusicon**
I figured someone may like this theme as it's one of two Microsoft created dark mode themes for XP. I tried to faithfully recreate the theme based on screenshots from Windows XP installation and resources unpacked from msstyles. I used Windows XP style as a base XAML for it.

Screenshot:
RoyaleNoir

### CODE REVIEW

**Review by dremin — CHANGES_REQUESTED** [review]
Hey, this is great, thanks! I do see some minor issues, if you're able to fix them, that would be awesome, otherwise let me know and I can give it a go.

- The background when the taskbar is on the left or right does not match the msstyles
- The taskbar gradient doesn't align with the start button gradient
- The border of taskbar/quick launch buttons isn't quite right. In the msstyles, the border is never lighter than the background
- The above item may actually be the taskbar background being too dark?
- The quick launch button right border is using the color that should be on the bottom border

**Comment by lpmusicon** [comment]
I will look into it and try to fix the issues :)

**Comment by ColdSalt09** [comment]
How I can use this theme? I made themes and resources folders but RetroBar crashes

**Comment by lpmusicon** [comment]
Hey, It should work as expected, check Event Log for application crash. I didn't have much time lately, but will look into fixing those issues.

**Comment by dremin** [comment]
> How I can use this theme? I made themes and resources folders but RetroBar crashes

I just tried the same with the current release version of RetroBar and the theme loads. Here is my folder structure if it helps:

    .
    ├── RetroBar.exe
    ├── Resources
       ├── startnoir.png
       └── startxpblue.png
    └── Themes
       └── Windows XP Royal Noir.xaml

**Comment by dremin** [comment]
>     * The quick launch button right border is using the color that should be on the bottom border

Oops, this issue is actually in the Blue theme that was copied from (misnamed borders). I'll fix the Blue theme, which should also fix themes that include it as a base.

**Comment by ColdSalt09** [comment]
εικόνα
Thanks! Nice theme!

**Comment by dremin** [comment]
@lpmusicon are you still planning on making those changes? If not, please let me know and I can :)

**Comment by lpmusicon** [comment]
Hey @dremin yes. I had to take some overtime at work and was unable to look into it. This week will push an update

**Comment by xoascf** [comment]
@lpmusicon, that Start button looks ugly, does that button really look like that originally?

You've done a good job, you just need to fix what @dremin pointed out above.

**Comment by lpmusicon** [comment]
@xoascf I copied the graphics for Start button straight from msstyles. It's how it was in the original

**Comment by lpmusicon** [comment]
Hey @dremin , it's been a while.
* The background when the taskbar is on the left or right does not match the msstyles - Should be fixed now
* The taskbar gradient doesn't align with the start button gradient - Appears also to be fixed but is a bit blurry, not exactly 100% sharp
* The theme name should be Windows XP Royale Noir - Changed

* The border of taskbar/quick launch buttons isn't quite right. In the msstyles, the border is never lighter than the background
* The above item may actually be the taskbar background being too dark? I am comparing it to how it is rendered inside Windows XP VM, they look quite comparable to me. Please assist me with that if you still see some differences.

* The quick launch button right border is using the color that should be on the bottom border - I have some troubles with that, are you able to assist me with it? It seems Quick Launch border right is using the same property as bottom border and I don't quite see it in the XAML code.

obraz


If you see in any way It can be improved I think we can arrange that. Thanks for the patience. It's been quite busy life recently.

**Comment by dremin** [comment]
Thanks @lpmusicon! I have some small nits but I can address them after merge.

**Review by dremin — APPROVED** [review]

**Pull request merged**
