### PR TITLE
Add Simplified Chinese language

### PR DESCRIPTION
**Pull request by wcxu21**
Add Simplified Chinese language

### CODE REVIEW

**Comment by xoascf** [comment]
You have to rename the translation XAML file as the actual native name of your language as explained here:
https://github.com/dremin/RetroBar/pull/72#issue-984717341

**Comment by dremin** [comment]
Thanks @wcxu21!

@xoascf - Do you see any issue with me merging this now, then we can rename the file in a followup?

**Comment by xoascf** [comment]
> @xoascf - Do you see any issue with me merging this now, then we can rename the file in a followup?

Okay, I guess there is no problem apart from the file name, we will rename it later.

**Comment by dremin** [comment]
Thanks @wcxu21 for the translation! Closing this as it has been merged under #116.

**Pull request closed without merging**
