### PR TITLE
Add German translation

### PR DESCRIPTION
**Pull request by 0x5066**
This adds a somewhat rough German translation to Retrobar, I'm sure someone out there who's German will spot a mistake. :)
It's based on the German version of Windows XP.

### CODE REVIEW

**Comment by 0x5066** [comment]
I'm unsure what to do about the access keys, since looking at screenshots from Windows XP's task bar settings they don't have any, so I've no idea where to place them.

**Comment by xoascf** [comment]
> I'm unsure what to do about the access keys, since looking at screenshots from Windows XP's task bar settings they don't have any, so I've no idea where to place them.

They do, look:
MsoftXPNoCopy

**Comment by 0x5066** [comment]
Odd, the screenshots I saw didn't have them, teaches me to get a German VM going... will update the file and see where to go from there

**Comment by dremin** [comment]
Thanks!

**Pull request merged**
