### PR TITLE
Use XP-style properties window layout

### PR DESCRIPTION
**Pull request by dremin**
This should make adding new languages easier, since the properties images are no longer used in favor of a real themed preview:

Screenshot 2022-01-16 191104

I didn't re-use most of the UserControls here because they add a lot of extra heft in the code-behind, when all we really need is a simplified version of the markup.

@xoascf - Thoughts? I've kept the properties images in tree for now just in case.

### CODE REVIEW

**Comment by xoascf** [comment]
I really like it, I was specifically looking forward to this!

**Comment by xoascf** [comment]
One more thing, while we're at it, it would be better to try to work everything with XAML, I don't know if @Splitwirez will still be willing regarding the redesign of the XP Start button (#10)

**Comment by xoascf** [comment]
There is only one problem with the design about the checkboxes, we should use toggle switches, or keep the checkboxes and use the preview simply as a preview by adding two more buttons that do their job (Apply and Cancel), [check this](https://uxplanet.org/checkbox-vs-toggle-switch-7fc6e83f10b8).

**Comment by xoascf** [comment]
Regarding font smoothing, it should be something that affects the context menus as well, and the preview should also be affected.

**Comment by dremin** [comment]
> One more thing, while we're at it, it would be better to try to work everything with XAML, I don't know if @Splitwirez will still be willing regarding the redesign of the XP Start button (#10)



> There is only one problem with the design about the checkboxes, we should use toggle switches, or keep the checkboxes and use the preview simply as a preview by adding two more buttons that do their job (Apply and Cancel), [check this](https://uxplanet.org/checkbox-vs-toggle-switch-7fc6e83f10b8).

Yes, but we can do these in separate PRs.

**Pull request merged**
