### PR TITLE
Add option to use software rendering

### PR DESCRIPTION
**Pull request by dremin**
This option should allow users affected by #57 (also #130) to use RetroBar normally.

### CODE REVIEW

**Comment by xoascf** [comment]
I'm not entirely sure, but I think you can make this change at runtime, without needing to restart RetroBar.

**Comment by dremin** [comment]
> I'm not entirely sure, but I think you can make this change at runtime, without needing to restart RetroBar.

You're right, it works! I assumed it didn't.

**Comment by dremin** [comment]
I suppose the question is, if there's graphical corruption does switching at runtime solve it? I wish I could reproduce the issue.

**Comment by xoascf** [comment]
> 
> 
> I suppose the question is, if there's graphical corruption does switching at runtime solve it? I wish I could reproduce the issue.

In that case, you could reinitialise or reload(?) the taskbar (or wait for the user to restart it) to be on the safe side.
It would be best to see if the people who reported this issue can find out from the artifact generated by changing that option.

**Pull request merged**
