### PR TITLE
Adding Vista Theme

### PR DESCRIPTION
**Pull request by markyb86**
image

Theme used XP Royale as a base

Copied XP Blue -> Controls\Vista Frame.xaml

Decreased width of start button to 40px
used blank PNG to remove the XP flag icon
used screen shots to match the taskbar gradient from vista
made system tray transparent as there isn't a variance in vista as there is in XP

needs: system tray toggle button themed

### CODE REVIEW

**Comment by xoascf** [comment]
Theme doesn't load.

**Comment by markyb86** [comment]
> Theme doesn't load. image

do you have "Vista Frame.xaml" in the controls folder, as well as startvista.png & startvistablue.png in the resources folder?
image

**Comment by mutoyoru** [comment]
I not a reviewer. I just took a look at it out of curiosity. And seems like it needs a lot of things to be fixed.

- You need to reference button icon in the project file. Otherwise theme won't load or crash when you're trying to select the theme in compiled versions. (like in Github Actions tab)
- Tray toggle looks just like in Royale. Tray toggle must be transparent like in Vista. Also the arrow's shape is different than XP.
- Taskbar background is not right. In Vista it looks a little bit glossy.
- Pressed Background, Hover Background, Pressed Hover Background, Flashing Background needs to be completely redone.
- The border of taskbar buttons isn't quite right.
- Vertical Taskbar Background hasn't been modified at all, it's just Royale colors.
- Start button needs to be bigger and it has a bulge that sticks out of the taskbar. And in Vista, start button has a border around it. 
- Start button tip is wrong. Vista has a different start button tip.
- Background and foreground of tool tips are different in Vista.
- Default font must be Segoe UI not Tahoma.
- You don't need a blank png. You can set Start Icon's property to hidden if you want.
- Why did you copied XP Blue as Vista Frame to Controls folder? That folder is unrelated to theme settings. You can just reference to Royale theme in xaml file instead of this.
- The theme name should be "Windows Vista Aero Basic", since it doesn't have any transparency.

That's all I've found. Maybe dremin could find the things I didn't noticed.

Also I recommend to completing the features and then opening the pull request if it's ready to be merged outside of little fixes. Otherwise set it's status to draft.

**Comment by markyb86** [comment]
image
I spent a bit of time trying to get the gradient correct. It's not going to look as glossy without transparency.

I copied the XP Blue theme as a base, as it contains the width of the start button information. If I reference Royale the start button will be the same width as Royale.

Without modification to the engine, the start button has to be small to fit the constraints of the 34px tall taskbar.

Appreciate the feedback. Maybe someone else will want to work on this theme.

**Comment by XTMYTYT** [comment]
coool

**Comment by ColdSalt09** [comment]
εικόνα
works

**Comment by MP36ctrl** [comment]
It keeps crashing for me, I put the files in the correct loctations: 
Controls/Vista Frame.xaml
Themes/Vista Ultimate.xaml
and all of the image resources in Resources.
Is there anything i am missing or any update?

**Pull request closed without merging**
