### PR TITLE
Add auto-hide feature

### PR DESCRIPTION
**Pull request by dremin**
Addresses the highly-requested #77.

Also added unlocked taskbar styles for XP themes when using auto-hide.

### CODE REVIEW

**Review by xoascf — COMMENTED** [review]
There should be no animation when you unhide the taskbar (it should appear immediately, as in Windows XP), because it seems to conflict with the work area, and if you press the Start button with the cursor while the animation is not finished, the Start menu (StartIsBack in this case) will appear in the corner, not inside the area.
hide_sev

In any case, the unhide animation appears in Windows Vista and later, but you cannot interact with the taskbar until it has finished.


The lines around the Start button in classic themes should not appear when hiding.
hide_ret

**Comment by 111ebobo** [comment]
> There should be no animation when you unhide the taskbar (it should appear immediately, as in Windows XP), because it seems to conflict with the work area, and if you press the Start button with the cursor while the animation is not finished, the Start menu (StartIsBack in this case) will appear in the corner, not inside the area. hide_sev
> 
> In any case, the unhide animation appears in Windows Vista and later, but you cannot interact with the taskbar until it has finished.
> 
> The lines around the Start button in classic themes should not appear when hiding. hide_ret

wait, is there are windows 7 theme? it shouldn`t be in retrobar

**Comment by dremin** [comment]
> There should be no animation when you unhide the taskbar (it should appear immediately, as in Windows XP), because it seems to conflict with the work area, and if you press the Start button with the cursor while the animation is not finished, the Start menu (StartIsBack in this case) will appear in the corner, not inside the area.
> hide_sev

Hm, the workarea never changes regardless when using auto-hide. I wonder how StartIsBack is positioning the start menu, because there is no appbar to position against. I don't believe adjusting the animation would resolve this.

As far as accuracy, adjusting the animation is possible, however making the taskbar appear immediately on hover can be annoying. Windows worked around that by adding a delay before showing the taskbar. Having the animation lets us keep the responsiveness without the annoyance, and I feel like the responsiveness is preferable, but I am open to input.

> The lines around the Start button in classic themes should not appear when hiding.
> hide_ret

I also noticed some undesirable tooltips while auto-hidden. I'm adding a "dummy" element that will gain focus when hiding to solve both problems.

**Comment by yereverluvinunclebert** [comment]
I would suggest that you add a check as to whether any other user-interaction is taking place just before the auto-hide occurs. At the moment it does not take into account that a drag operation is taking place from one part of the dock to another and auto-hides right in the middle of the drag, meaning that the drag is left hanging.

I would also suggest that you add an option to the auto-hide allowing the user to configure the number of seconds before auto-hide occurs. This would potentially alleviate theabove problem as a longer delay would give users time to drag and drop before the bar disappeared. A useful function in any case.

**Review by xoascf — APPROVED** [review]

**Comment by dremin** [comment]
> I would suggest that you add a check as to whether any other user-interaction is taking place just before the auto-hide occurs. At the moment it does not take into account that a drag operation is taking place from one part of the dock to another and auto-hides right in the middle of the drag, meaning that the drag is left hanging.
> 
> 
> 
> I would also suggest that you add an option to the auto-hide allowing the user to configure the number of seconds before auto-hide occurs. This would potentially alleviate theabove problem as a longer delay would give users time to drag and drop before the bar disappeared. A useful function in any case. 

Auto-hide should not occur during drag. Could you provide some more details as to the drag operation that is allowing auto-hide? I tested with both quick launch and taskbar buttons but wasn’t able to reproduce.

**Comment by yereverluvinunclebert** [comment]
Dragging within the taskbar to re-order the taskbar entries. I left click on a taskbar entry, hold the mouse down and drag it to a new position in the taskbar, the taskbar auto-hides almost immediately and I am left with the drag forbidden icon hanging over the desktop. Nothing left to do but release the drag. Nothing occurs as expected as dock/bar is now hidden.

Running 1.12.40+7ebe030ef3

**Comment by dremin** [comment]
> Dragging within the taskbar to re-order the taskbar entries. I left click on a taskbar entry, hold the mouse down and drag it to a new position in the taskbar, the taskbar auto-hides almost immediately and I am left with the drag forbidden icon hanging over the desktop. Nothing left to do but release the drag. Nothing occurs as expected as dock/bar is now hidden.
> 
> Running 1.12.40+7ebe030ef3 Win 10 Pro 19044.2965

Thanks, that explains it! That's an older version before it was fixed, try [this newer build](https://github.com/dremin/RetroBar/suites/13205520627/artifacts/719106404) instead.

**Comment by yereverluvinunclebert** [comment]
That's good. Tests very well, smooth scroll-out. Waits until user-interaction is complete. Very good.

**Pull request merged**
