### PR TITLE
Lativian Translation

### PR DESCRIPTION
**Pull request by WF4123**

### CODE REVIEW

**Review by dremin — CHANGES_REQUESTED** [review]
The file name should be changed to `latviešu.xaml` to allow this to work when the language is set to "System" and the Windows language is Latvian. Otherwise, this looks great!

**Comment by dremin** [comment]
@WF4123 Are you able to do the rename or would you prefer me to?

**Comment by WF4123** [comment]
> @WF4123 Are you able to do the rename or would you prefer me to?

I'll try.

**Review by dremin — APPROVED** [review]
Thanks!

**Pull request merged**
