### PR TITLE
NuGet Update & Translate the Start Button in French

### PR DESCRIPTION
**Pull request by VoXaN24**
I can translate the all apps if u needed too (I have overwrite the english translation be aware)

### CODE REVIEW

**Comment by VoXaN24** [comment]
French Translation added by overwrite the english one

**Comment by dremin** [comment]
Thanks for the translation! Once #72 is merged we can add French as a language that doesn't overwrite English.

**Comment by dremin** [comment]
@VoXaN24 I've added a French language in #101 using the support from #72. There are some missing translations for French due to new features, would you like to add the missing ones? You can compare to the Spanish translation.

**Comment by dremin** [comment]
Since the translations were incorporated into the new system, I am going to close this PR. Your work will be credited in the release notes.

**Pull request closed without merging**
