### PR TITLE
Added Slovak Language

### PR DESCRIPTION
**Pull request by SAMUELLL41**

### CODE REVIEW

**Review by xoascf — CHANGES_REQUESTED** [review]
The correct name of the XAML translation file should be `slovenčina.xaml`.
Some translations are also missing. Please [check the source file](https://github.com/dremin/RetroBar/blob/master/RetroBar/Languages/English.xaml) and update your translation accordingly.

**Comment by SAMUELLL41** [comment]
I think there is a bit of chaos with the naming of languages. Some of them have the first letter uppercase, some don't.

**Comment by xoascf** [comment]
> I think there is a bit of chaos with the naming of languages. Some of them have the first letter uppercase, some don't.

This is so that "System" can be used as the language and the appropriate translation can be loaded.
If your system is set to the language of this translation, you can verify that the name is correct by running:
`powershell [System.Globalization.CultureInfo]::CurrentUICulture.Parent.NativeName`

**Comment by xoascf** [comment]
Good work @SAMUELLL41, thanks!

**Pull request merged**
