### PR TITLE
Use XAML instead of raster image for XP Blue startbutton background

### PR DESCRIPTION
**Pull request by Splitwirez**
The start button looks like this now: image

**PROS** of this change
- Arguably legally safer, as that's one copyright-protected asset no longer used without authorization (albeit the logos are probably a greater reason for concern)
- Arguably etter for DPI scaling
- Looks much better than before when the text is longer than just..."start" (good for localization - Windows XP in French, for example, says "démarrer", resulting in a noticeably wider start button)

**CONS** of this change
- If you take a screenshot of this button and the original, and lay one atop the other in an image editor, you'll probably be able to tell which one is which by looking at them, provided you have even a remotely keen eye for such things

EDIT: I should probably note that this isn't totally new, it was taken from an old long-dead project of mine. I'd love to see some of my work for that find itself a new home where it will actually see the light of day.

### CODE REVIEW

**Comment by AfoninZ** [comment]
Vectorized FTW! By the way, would that allow for proper interface scaling at HiDPI?

**Comment by Splitwirez** [comment]
> By the way, would that allow for proper interface scaling at HiDPI (as in, keeping the original shape of the button and stuff)?

Yes, as noted in the initial post.

**Comment by dremin** [comment]
Thanks! It looks good for the most part, but is a bit too light. I'd like this to be a bit closer in appearance to the original before merging if possible.

**Comment by Splitwirez** [comment]
> Thanks! It looks good for the most part, but is a bit too light. I'd like this to be a bit closer in appearance to the original before merging if possible.

Glad to hear it.

I'll get on that as soon as possible.

**Comment by Splitwirez** [comment]
@dremin I am so sorry for the absurdly long delay. I've tweaked the colour as you'd requested, so...hopefully that'll do it, but if not, I'm all ears as to what else needs adjusting.

**Comment by dremin** [comment]
Thanks! I took a look at the tweaks, and unfortunately there is still just too much difference between the raster and vector appearance in its current state. Here's a comparison of each state (this PR is on the right). The biggest differences are the text shadow and position, the top and bottom gradients, and the pressed state.

comparison

**Comment by Splitwirez** [comment]
> comparison

...okay, that's just plain embarrassing. I'll get on that ASAP.

**Comment by achmadsutardi441953** [comment]
ewfsdf
This Start button classic icons?

**Comment by Splitwirez** [comment]
FYI I've purged and recreated my fork of RetroBar, so I could move my work on that towards this PR to a new branch (previously I'd mistakenly begun work on `master`). That branch can be found here: https://github.com/Splitwirez/RetroBar/tree/xaml-luna-skin


That said...I've come to realize that this PR was started based on my assumption that the goal of RetroBar was in line with my own prior work - that is, that legal safety (and arguably visual fidelity) ought to take precedence over pixel-perfect accuracy, flaws and all. I've since learned that this is not the case. As such, I don't *intend* to finish this PR of my own accord. If you'd still like to see the PR completed so it can be merged, do let me know. Until then, consider it shelved.

That said, I'd still like to pitch in, in whatever other small ways I can...whatever that might end up meaning.

**Comment by xoascf** [comment]
It seems that it is not possible to continue with this PR, as the branch has been deleted and rewritten with the original one (maybe the changes are just gone, but this PR is "floating" for some reason?), GitHub reports the `Splitwirez:master` repository as deleted, maybe it is a good idea to start this from scratch.

**Pull request closed without merging**
