### PR TITLE
Multiple Monitor Support

### PR DESCRIPTION
**Pull request by SIX10**
Adds support for multiple monitors. Right now it does it by default, looking to make it into a toggle option in the future. Quick and dirty, probably not the best way to do it but it works flawlessly.

### CODE REVIEW

**Comment by xoascf** [comment]
- It has some problems when changing the positions of the taskbar (when starting it with 2 monitors, and changing the positions, they were not correct for my second monitor in my case)
- Sometimes, when exiting, it makes Windows Explorer go black (no desktop and no wallpaper, when restarting Explorer it goes back to normal)
- When switching from two to one monitor, the second taskbar still appears and does not disappear as a window
- When you start with one monitor and switch to two monitors, it is only displayed on the first monitor

Perhaps some kind of dynamic reloading is needed to fix the above two problems.

**Comment by SIX10** [comment]
> 
> 
>     * It has some problems when changing the positions of the taskbar (when starting it with 2 monitors, and changing the positions, they were not correct for my second monitor in my case)
> 
>     * Sometimes, when exiting, it makes Windows Explorer go black (no desktop and no wallpaper, when restarting Explorer it goes back to normal)
> 
>     * When switching from two to one monitor, the second taskbar still appears and does not disappear as a window
> 
>     * When you start with one monitor and switch to two monitors, it is only displayed on the first monitor
> 
> 
> Perhaps some kind of dynamic reloading is needed to fix the above two problems.

I'll check out the positioning problem. I've exited Retrobar plenty of times without any problem to explorer, but I'll try and see what that's about. I don't know about switching from one screen to two or vice versa, as I don't think ManagedShell can detect when a screen is disconnected/connected.

**Comment by dremin** [comment]
This approach won't be sufficient for supporting changes in the display setup while RetroBar is running, and I'd like to have this be configurable. ManagedShell AppBarWindows do detect display changes; we can bring over some of the window manager code from Cairo to support this in a more robust manner.

**Comment by dremin** [comment]
I added a more robust implementation with PR #149. Feel free to give the build on that PR a try and see if it works well for you.

**Comment by dremin** [comment]
@SIX10 OK to close this?

**Comment by SIX10** [comment]
> @SIX10 OK to close this?

Oops, yep!

**Pull request closed without merging**
